name = "Manual_Hearthstone_asdagigafo"
display_name = "Manual: Hearthstone"
home = "https://discord.com/channels/1097532591650910289/1406539265105596506"
default_url = "https://github.com/vingo5star/Hearthstone-Manual/releases/download/v{{version}}/manual_hearthstone_asdagigafo.apworld"

[versions]

"0.0.1" = {}